# Generated by Django 5.1.7 on 2025-03-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('seller', 'seller'), ('buyer', 'buyer')], default='buyer', max_length=10),
        ),
    ]
