# Generated by Django 5.1.7 on 2025-03-26 12:15

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0003_alter_brand_brand_name_alter_model_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_auction', to='car_app.car'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Бензин', 'Бензин'), ('Дизель', 'Дизель'), ('Газ', 'Газ'), ('Электро', 'Электро'), ('Гибрид', 'Гибрид')], max_length=14),
        ),
    ]
